# Generated by Django 5.2.14 on 2026-05-16 00:45

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorpusVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        help_text="Versioned by date or by corpus commit hash, e.g. 2026-05-10",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("released_at", models.DateTimeField(help_text="When this corpus version was released")),
                ("laws_count", models.PositiveIntegerField(help_text="Total laws in this version")),
                ("articles_count", models.PositiveIntegerField(help_text="Total indexed articles")),
                ("chunks_count", models.PositiveIntegerField(help_text="Total vectorized chunks")),
                ("manifest", models.JSONField(help_text="List of included laws with their identifiers")),
                ("changelog", models.TextField(blank=True, default="", help_text="Summary of changes")),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="Exactly one corpus version may be active at a time"),
                ),
            ],
            options={
                "verbose_name": "Corpus Version",
                "verbose_name_plural": "Corpus Versions",
                "db_table": "corpus_version",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_corpus_version_active_singleton",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalChunk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("law_id", models.CharField(help_text="Slug of the parent LegalDocument", max_length=64)),
                ("article_number", models.CharField(help_text="E.g. 'Art. 4', 'Art. 18'", max_length=32)),
                ("anchor", models.CharField(help_text="Anchor slug, e.g. 'art-4'", max_length=64)),
                ("text_paraphrased", models.TextField(help_text="Curated paraphrase shown to the user")),
                (
                    "text_verbatim",
                    models.TextField(blank=True, default="", help_text="Verbatim article text (may be long)"),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=384, help_text="384-dim embedding of the paraphrased text"
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="Filter tags, e.g. ['warranty','eviction']",
                        size=None,
                    ),
                ),
                (
                    "relevance_for_findings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="Finding categories where this chunk applies",
                        size=None,
                    ),
                ),
                (
                    "severity_hint",
                    models.CharField(
                        blank=True,
                        choices=[("critical", "Crítica"), ("red", "Roja"), ("yellow", "Amarilla")],
                        help_text="Suggested severity if the contract fails this article",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "corpus_version",
                    models.ForeignKey(
                        db_column="corpus_version",
                        help_text="Corpus version this chunk belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="corpus.corpusversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Chunk",
                "verbose_name_plural": "Legal Chunks",
                "db_table": "legal_chunk",
                "indexes": [
                    models.Index(fields=["corpus_version"], name="idx_legal_chunk_corpus_version"),
                    models.Index(fields=["law_id"], name="idx_legal_chunk_law_id"),
                    django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="idx_legal_chunk_tags"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["relevance_for_findings"], name="idx_legal_chunk_relevance"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("corpus_version", "law_id", "anchor"), name="uq_legal_chunk_corpus_law_anchor"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("law_id", models.CharField(help_text="Slug, e.g. ley-inquilinato", max_length=64)),
                ("title", models.TextField(help_text="Official title")),
                (
                    "short_title",
                    models.CharField(blank=True, default="", help_text="Short title for citations", max_length=128),
                ),
                (
                    "decree",
                    models.CharField(blank=True, default="", help_text="Decree number and date", max_length=128),
                ),
                ("issued_at", models.DateField(blank=True, help_text="Original issuance date", null=True)),
                (
                    "official_gazette",
                    models.CharField(
                        blank=True, default="", help_text="Reference to the official gazette", max_length=256
                    ),
                ),
                (
                    "last_verified",
                    models.DateField(blank=True, help_text="Last date verified against official source", null=True),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, default="", help_text="URL of the official source", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_force", "Vigente"),
                            ("repealed", "Derogada"),
                            ("in_force_with_amendments", "Vigente con reformas"),
                        ],
                        default="in_force",
                        help_text="Current status of the law",
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", help_text="Area of law", max_length=128)),
                (
                    "corpus_version",
                    models.ForeignKey(
                        db_column="corpus_version",
                        help_text="Corpus version this document snapshot belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="corpus.corpusversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Document",
                "verbose_name_plural": "Legal Documents",
                "db_table": "legal_document",
                "indexes": [models.Index(fields=["corpus_version"], name="idx_ldoc_corpus_version")],
                "constraints": [
                    models.UniqueConstraint(fields=("law_id", "corpus_version"), name="uq_legal_document_law_corpus"),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["in_force", "repealed", "in_force_with_amendments"])),
                        name="ck_legal_document_status_enum",
                    ),
                ],
            },
        ),
    ]
