# Generated by Django 5.2.14 on 2026-05-18 00:10

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0005_embedding_dim_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                dimensions=1024, help_text="1024-dim e5-large embedding of the paraphrased text"
            ),
        ),
    ]
