# Generated by Django 5.2.14 on 2026-05-16 00:45

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BenchmarkVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        help_text="Semver or date-based version, e.g. 2026-Q2",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("released_at", models.DateTimeField(help_text="When this benchmark version was published")),
                (
                    "changelog",
                    models.TextField(blank=True, default="", help_text="Summary of changes vs prior version"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Exactly one benchmark version may be active at a time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Benchmark Version",
                "verbose_name_plural": "Benchmark Versions",
                "db_table": "benchmark_version",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_benchmark_version_active_singleton",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EconomicBenchmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "benchmark_key",
                    models.CharField(help_text="Stable key, e.g. 'bank_mortgage_rate_max'", max_length=64),
                ),
                (
                    "value_min",
                    models.DecimalField(
                        blank=True, decimal_places=4, help_text="Lower bound (nullable)", max_digits=18, null=True
                    ),
                ),
                (
                    "value_max",
                    models.DecimalField(
                        blank=True, decimal_places=4, help_text="Upper bound (nullable)", max_digits=18, null=True
                    ),
                ),
                (
                    "value_default",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Recommended single value (nullable)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pct", "Porcentaje"),
                            ("usd", "USD"),
                            ("months", "Meses"),
                            ("multiplier", "Multiplicador"),
                            ("ratio", "Ratio"),
                        ],
                        help_text="Unit of the value (pct, usd, months, multiplier, ratio)",
                        max_length=16,
                    ),
                ),
                (
                    "applicable_contract_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        help_text="Contract types this benchmark applies to",
                        size=None,
                    ),
                ),
                ("source", models.TextField(help_text="Source citation (e.g. BCR table, SSF circular)")),
                ("source_url", models.URLField(blank=True, default="", help_text="URL of the source", max_length=512)),
                ("last_updated", models.DateField(help_text="When the underlying market figure was last refreshed")),
                ("next_review_due", models.DateField(help_text="When the next benchmark review is scheduled")),
                (
                    "benchmark_version",
                    models.ForeignKey(
                        db_column="benchmark_version",
                        help_text="Version this benchmark belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benchmarks",
                        to="economics.benchmarkversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Economic Benchmark",
                "verbose_name_plural": "Economic Benchmarks",
                "db_table": "economic_benchmark",
                "indexes": [
                    models.Index(fields=["benchmark_version"], name="idx_economic_benchmark_version"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["applicable_contract_types"], name="idx_economic_benchmark_types"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("benchmark_key", "benchmark_version"), name="uq_economic_benchmark_key_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit__in", ["pct", "usd", "months", "multiplier", "ratio"])),
                        name="ck_economic_benchmark_unit_enum",
                    ),
                ],
            },
        ),
    ]
