# Generated by Django 5.2.14 on 2026-05-16 00:45

import django.contrib.postgres.fields
import django.db.models.deletion
import platform_core.infrastructure.django.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corpus", "0001_initial"),
        ("economics", "0001_initial"),
        ("rubric", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobExecutionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "job_name",
                    models.CharField(
                        help_text="Celery task name (e.g. platform.anonymize_old_analyses)", max_length=128
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, help_text="When the job started")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the job ended (NULL if still running)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Iniciado"),
                            ("success", "Éxito"),
                            ("partial", "Parcial"),
                            ("failed", "Fallido"),
                        ],
                        help_text="Outcome",
                        max_length=16,
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(blank=True, help_text="Records touched by this run", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", help_text="Truncated error trail for failures"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=platform_core.infrastructure.django.models._job_log_default_expiry,
                        help_text="When this row may be purged (default: started_at + 30 days)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Execution Log Entry",
                "verbose_name_plural": "Job Execution Log",
                "db_table": "job_execution_log",
                "indexes": [
                    models.Index(fields=["job_name", "started_at"], name="idx_jobs_started"),
                    models.Index(fields=["expires_at"], name="idx_jobs_expires"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivacyAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("analysis_anonymized", "Análisis anonimizado"),
                            ("delivery_target_purged", "Destino de entrega purgado"),
                            ("submission_purged", "Submission transitoria purgada"),
                            ("ocr_job_purged", "OCR job purgado"),
                            ("delivery_request_purged", "DeliveryRequest purgado"),
                            ("link_expired", "Enlace público expirado"),
                            ("resend_requested", "Reenvío solicitado por usuario"),
                        ],
                        help_text="What kind of privacy event was recorded",
                        max_length=64,
                    ),
                ),
                (
                    "related_id",
                    models.UUIDField(
                        blank=True, help_text="ID of the affected row (e.g. analysis_id) if applicable", null=True
                    ),
                ),
                (
                    "related_table",
                    models.CharField(
                        blank=True, help_text="Table the related_id belongs to", max_length=128, null=True
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, help_text="Additional structured context; must not contain PII", null=True
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        help_text="Actor/process that triggered the event (job name, capability holder hash, etc.)",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, help_text="When the event was logged")),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=platform_core.infrastructure.django.models._audit_default_expiry,
                        help_text="When this row may be purged (default: occurred_at + 1 year)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Audit Log Entry",
                "verbose_name_plural": "Privacy Audit Log",
                "db_table": "privacy_audit_log",
                "indexes": [
                    models.Index(fields=["event_type"], name="idx_audit_event"),
                    models.Index(fields=["occurred_at"], name="idx_audit_occurred"),
                    models.Index(fields=["expires_at"], name="idx_audit_expires"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "event_type__in",
                                [
                                    "analysis_anonymized",
                                    "delivery_target_purged",
                                    "submission_purged",
                                    "ocr_job_purged",
                                    "delivery_request_purged",
                                    "link_expired",
                                    "resend_requested",
                                ],
                            )
                        ),
                        name="ck_privacy_audit_event_enum",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("canonical_name", models.TextField(help_text="Name as it typically appears in contracts")),
                (
                    "normalized_name",
                    models.TextField(
                        help_text="Normalized slug used as the matching key for incoming analyses", unique=True
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the project was first created in the system"
                    ),
                ),
                (
                    "last_analyzed",
                    models.DateTimeField(help_text="Last time an analysis was associated with this project"),
                ),
                (
                    "total_analyses",
                    models.PositiveIntegerField(default=0, help_text="Count of analyses associated (denormalized)"),
                ),
                (
                    "avg_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Moving average of associated total scores (recomputed by retention job)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "score_distribution",
                    models.JSONField(
                        blank=True, default=dict, help_text="Count by band: {green: N, yellow: M, red: K}"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Extensible; must never contain PII"),
                ),
                (
                    "last_recomputed_at",
                    models.DateTimeField(
                        blank=True, help_text="When avg_score / score_distribution were last recomputed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "project",
                "indexes": [
                    models.Index(fields=["normalized_name"], name="idx_project_normalized"),
                    models.Index(fields=["last_analyzed"], name="idx_project_last_analyzed"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractAnalysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "public_short_id",
                    models.CharField(
                        help_text="Public-facing short ID, format CS-YYYY-XXXXXX", max_length=24, unique=True
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("CVC", "Compraventa al contado"),
                            ("CVP", "Compraventa a plazos"),
                            ("ARV", "Arrendamiento de vivienda"),
                            ("ARC", "Arrendamiento de local comercial"),
                            ("APV", "Arrendamiento con promesa de venta"),
                            ("LEA", "Arrendamiento financiero / leasing"),
                            ("IVU", "Contrato institucional IVU"),
                            ("FSV", "Compra o préstamo financiado por FSV"),
                            ("NOT_CLASSIFIABLE", "No clasificable"),
                        ],
                        help_text="Final detected contract type",
                        max_length=16,
                    ),
                ),
                (
                    "contract_type_declared",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CVC", "Compraventa al contado"),
                            ("CVP", "Compraventa a plazos"),
                            ("ARV", "Arrendamiento de vivienda"),
                            ("ARC", "Arrendamiento de local comercial"),
                            ("APV", "Arrendamiento con promesa de venta"),
                            ("LEA", "Arrendamiento financiero / leasing"),
                            ("IVU", "Contrato institucional IVU"),
                            ("FSV", "Compra o préstamo financiado por FSV"),
                            ("NOT_CLASSIFIABLE", "No clasificable"),
                        ],
                        help_text="Type the document claims to be (may differ if reclassified)",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "contract_type_reclassified",
                    models.BooleanField(default=False, help_text="Whether reclassification occurred (F2)"),
                ),
                (
                    "reclassification_reason",
                    models.TextField(
                        blank=True, default="", help_text="Justification for reclassification, citing indicators"
                    ),
                ),
                (
                    "score_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Final score 0-10. NULL while rubric pending; populated by F4 finalize.",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("green", "Verde (8.0 - 10.0)"),
                            ("yellow", "Amarillo (5.0 - 7.9)"),
                            ("red", "Rojo (0 - 4.9)"),
                            ("not_analyzable", "No analizable"),
                        ],
                        help_text="Final band (NULL until rubric completes)",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "override_triggered",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="List of active override codes (F4 fills)",
                        size=None,
                    ),
                ),
                (
                    "scores_by_category",
                    models.JSONField(blank=True, default=list, help_text="Array of CategoryScore (DOMAIN §5.1)"),
                ),
                (
                    "criterion_evaluations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of CriterionEvaluation (DOMAIN §5.2); reduced to per-category aggregate at anonymization",
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of Finding (DOMAIN §5.3); reduced to severity counts at anonymization",
                    ),
                ),
                ("findings_count", models.PositiveIntegerField(default=0, help_text="Total findings (denormalized)")),
                (
                    "critical_findings_count",
                    models.PositiveIntegerField(default=0, help_text="Count of `critical` severity findings"),
                ),
                (
                    "unverifiable_count",
                    models.PositiveIntegerField(default=0, help_text="Count of unverifiable criteria"),
                ),
                (
                    "economic_summary",
                    models.JSONField(
                        blank=True, help_text="EconomicSummary (DOMAIN §5.5); bucketed at anonymization", null=True
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("queued", "Encolada"),
                            ("sent_email", "Enviado por email"),
                            ("sent_whatsapp", "Enviado por WhatsApp"),
                            ("available_link", "Disponible vía enlace"),
                            ("expired", "Expirada"),
                            ("failed", "Fallida"),
                        ],
                        default="pending",
                        help_text="Report delivery state (canonical per PRD_F8 §5.1)",
                        max_length=16,
                    ),
                ),
                (
                    "delivery_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email_pdf", "PDF por email"),
                            ("whatsapp_summary", "Resumen por WhatsApp"),
                            ("web_link", "Enlace web"),
                        ],
                        help_text="Channel chosen by the user",
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "delivery_target_hash",
                    models.CharField(
                        blank=True,
                        help_text="Salt+SHA-256 hash of email or phone; erased at anonymization",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "link_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Web link expiration (LINK_TTL_DAYS=30 default)", null=True
                    ),
                ),
                (
                    "resend_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of resend attempts (capped at 3 in service layer)"
                    ),
                ),
                ("anonymized_at", models.DateTimeField(blank=True, help_text="If anonymized, when", null=True)),
                (
                    "submission_hash",
                    models.CharField(
                        help_text="SHA-256 of the original contract (idempotency; preserved after anonymization)",
                        max_length=64,
                    ),
                ),
                (
                    "benchmark_version",
                    models.ForeignKey(
                        blank=True,
                        db_column="benchmark_version",
                        help_text="Benchmark version used (nullable for contract types that skip economics)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="economics.benchmarkversion",
                    ),
                ),
                (
                    "corpus_version",
                    models.ForeignKey(
                        db_column="corpus_version",
                        help_text="Corpus version used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="corpus.corpusversion",
                    ),
                ),
                (
                    "rubric_version",
                    models.ForeignKey(
                        db_column="rubric_version",
                        help_text="Rubric version used (PROTECT: catalog rows cannot be deleted while referenced)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="rubric.rubricversion",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this analysis is associated with",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="platform_core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Analysis",
                "verbose_name_plural": "Contract Analyses",
                "db_table": "contract_analysis",
                "indexes": [
                    models.Index(fields=["project"], name="idx_analysis_project"),
                    models.Index(fields=["public_short_id"], name="idx_analysis_short_id"),
                    models.Index(fields=["submission_hash"], name="idx_analysis_subhash"),
                    models.Index(fields=["created_at"], name="idx_analysis_created"),
                    models.Index(
                        condition=models.Q(("link_expires_at__isnull", False)),
                        fields=["link_expires_at"],
                        name="idx_analysis_link_exp",
                    ),
                    models.Index(
                        condition=models.Q(("anonymized_at__isnull", True)),
                        fields=["anonymized_at"],
                        name="idx_analysis_anon",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score_total__isnull", True),
                            models.Q(("score_total__gte", 0), ("score_total__lte", 10)),
                            _connector="OR",
                        ),
                        name="ca_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("band__isnull", True),
                            ("band__in", ["green", "yellow", "red", "not_analyzable"]),
                            _connector="OR",
                        ),
                        name="ck_contract_analysis_band_enum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "delivery_status__in",
                                [
                                    "pending",
                                    "queued",
                                    "sent_email",
                                    "sent_whatsapp",
                                    "available_link",
                                    "expired",
                                    "failed",
                                ],
                            )
                        ),
                        name="ck_contract_analysis_delivery_status_enum",
                    ),
                ],
            },
        ),
    ]
