# Generated by Django 5.2.14 on 2026-05-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_core", "0008_retention_audit_constraint_and_beat"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="privacyauditlog",
            name="uq_privacy_audit_analysis_anonymized_related",
        ),
    ]
