# Generated by Django 5.2.14 on 2026-05-16 00:45

import delivery.infrastructure.django.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email_pdf", "PDF por email"),
                            ("whatsapp_summary", "Resumen por WhatsApp"),
                            ("web_link", "Enlace web"),
                        ],
                        help_text="Channel chosen by the user",
                        max_length=24,
                    ),
                ),
                (
                    "target_hash",
                    models.CharField(
                        help_text="Salt+SHA-256 hash of email or phone (preserved for resend capability checks)",
                        max_length=128,
                    ),
                ),
                (
                    "target_value_encrypted",
                    models.TextField(
                        blank=True,
                        help_text="KMS-encrypted destination. Erased on successful delivery or +24h, whichever first.",
                        null=True,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the user requested delivery"),
                ),
                ("delivered_at", models.DateTimeField(blank=True, help_text="When delivery succeeded", null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0, help_text="Delivery attempts made")),
                ("max_attempts", models.PositiveSmallIntegerField(default=3, help_text="Hard cap on retries")),
                (
                    "next_attempt_not_before",
                    models.DateTimeField(
                        blank=True,
                        help_text="Backoff gate: next attempt may only happen after this timestamp",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Encolada"),
                            ("sending", "Enviando"),
                            ("delivered", "Entregada"),
                            ("failed", "Fallida"),
                            ("expired", "Expirada"),
                        ],
                        default="queued",
                        help_text="Lifecycle status (distinct from ContractAnalysis.delivery_status)",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="", help_text="Truncated last error message")),
                (
                    "last_error_classification",
                    models.CharField(
                        blank=True,
                        choices=[("transient", "Transitorio (retry)"), ("permanent", "Permanente (no retry)")],
                        help_text="Whether the failure is transient (retry) or permanent",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=delivery.infrastructure.django.models._delivery_default_expiry,
                        help_text="Cleanup job purges rows past this timestamp (default +7d)",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="The analysis being delivered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_requests",
                        to="platform_core.contractanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Request",
                "verbose_name_plural": "Delivery Requests",
                "db_table": "delivery_request",
                "indexes": [
                    models.Index(fields=["analysis"], name="idx_delivery_analysis"),
                    models.Index(fields=["status"], name="idx_delivery_status"),
                    models.Index(fields=["expires_at"], name="idx_delivery_expires"),
                    models.Index(
                        condition=models.Q(("status", "queued"), ("next_attempt_not_before__isnull", False)),
                        fields=["next_attempt_not_before"],
                        name="idx_delivery_next_attempt",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("channel__in", ["email_pdf", "whatsapp_summary", "web_link"])),
                        name="ck_delivery_channel_enum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["queued", "sending", "delivered", "failed", "expired"])),
                        name="ck_delivery_status_enum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("last_error_classification__isnull", True),
                            ("last_error_classification__in", ["transient", "permanent"]),
                            _connector="OR",
                        ),
                        name="ck_delivery_error_classification_enum",
                    ),
                ],
            },
        ),
    ]
