# Generated by Django 5.2.14 on 2026-05-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_deliveryrequest_is_resend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="is_resend",
            field=models.BooleanField(
                default=False, help_text="True when enqueued via guarded resend endpoint (CS-248)"
            ),
        ),
    ]
