# Generated by Django 5.2.14 on 2026-05-17 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserErrorReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "public_short_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional analysis ID the report references (CS-YYYY-XXXXXX).",
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("classification", "classification"),
                            ("citation", "citation"),
                            ("economic_figure", "economic_figure"),
                            ("ui", "ui"),
                            ("other", "other"),
                        ],
                        help_text="Topic the user is reporting about (CS-336 enum).",
                        max_length=32,
                    ),
                ),
                ("description_excerpt", models.TextField(help_text="Free-text description, capped at 2000 chars.")),
                (
                    "contact_email_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the contact email (never stored in clear).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        help_text="SHA-256 of the requester IP — used only for rate limits and dedupe.", max_length=64
                    ),
                ),
                (
                    "consent_to_contact",
                    models.BooleanField(
                        default=False, help_text="Whether the user opted in to be contacted back about the report."
                    ),
                ),
                (
                    "user_agent_excerpt",
                    models.CharField(
                        blank=True, help_text="Truncated User-Agent header for triage.", max_length=200, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the report was filed.")),
            ],
            options={
                "db_table": "user_error_report",
                "indexes": [
                    models.Index(fields=["public_short_id"], name="idx_uer_short_id"),
                    models.Index(fields=["category"], name="idx_uer_category"),
                    models.Index(fields=["created_at"], name="idx_uer_created"),
                    models.Index(fields=["ip_hash"], name="idx_uer_ip_hash"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("category__in", ["classification", "citation", "economic_figure", "ui", "other"])
                        ),
                        name="uer_category_valid",
                    )
                ],
            },
        ),
    ]
