# Generated by Django 5.2.14 on 2026-05-16 00:45

import django.db.models.deletion
import ingestion.infrastructure.django.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "submission_hash",
                    models.CharField(
                        help_text="SHA-256 of the original file (idempotency key)", max_length=64, unique=True
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("jpg", "JPG"),
                            ("jpeg", "JPEG"),
                            ("png", "PNG"),
                            ("heic", "HEIC"),
                            ("webp", "WebP"),
                        ],
                        help_text="One of pdf|jpg|jpeg|png|heic|webp",
                        max_length=8,
                    ),
                ),
                ("file_size_bytes", models.PositiveIntegerField(help_text="Size in bytes (pre-OCR)")),
                (
                    "file_count",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of files attached (1-50 per CS-025)"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total page count once known (NULL for images)", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "Web"), ("whatsapp", "WhatsApp")],
                        default="web",
                        help_text="Channel the submission arrived on",
                        max_length=16,
                    ),
                ),
                (
                    "disclaimer_accepted_at",
                    models.DateTimeField(help_text="When the user acknowledged the disclaimer (BR-07)"),
                ),
                (
                    "disclaimer_method",
                    models.CharField(
                        choices=[("checkbox", "Checkbox en UI"), ("whatsapp_reply", "Confirmación en WhatsApp")],
                        default="checkbox",
                        help_text="How the disclaimer was accepted",
                        max_length=24,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, help_text="When the file landed")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Recibido"),
                            ("extracting", "Extrayendo texto"),
                            ("extracted", "Texto extraído"),
                            ("classifying", "Clasificando"),
                            ("analyzing", "Analizando"),
                            ("completed", "Completado"),
                            ("failed_extraction", "Falló extracción"),
                            ("failed_classification", "Falló clasificación"),
                            ("failed_analysis", "Falló análisis"),
                            ("rejected_language", "Rechazado por idioma"),
                            ("rejected_type", "Rechazado por tipo de contrato"),
                            ("rejected_size", "Rechazado por tamaño"),
                            ("expired", "Expirado"),
                        ],
                        default="received",
                        help_text="Pipeline state",
                        max_length=32,
                    ),
                ),
                (
                    "extraction_strategy_attempted",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pypdf", "pypdf (PDF con texto extraíble)"),
                            ("vision_llm", "Vision LLM (OpenRouter)"),
                            ("tesseract", "Tesseract local (fallback)"),
                        ],
                        help_text="Last extraction strategy tried",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "extraction_strategy_successful",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pypdf", "pypdf (PDF con texto extraíble)"),
                            ("vision_llm", "Vision LLM (OpenRouter)"),
                            ("tesseract", "Tesseract local (fallback)"),
                        ],
                        help_text="Extraction strategy that succeeded (NULL if all failed)",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "extracted_text_token_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Audit-only count. The text itself is NEVER persisted.", null=True
                    ),
                ),
                (
                    "extracted_text_language",
                    models.CharField(
                        blank=True,
                        help_text="Detected ISO 639-1 code (e.g. 'es', 'en'). Non-Spanish triggers rejection.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "error_reason",
                    models.TextField(blank=True, default="", help_text="Human-readable failure description"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, default="", help_text="Stable error code per CS-009 error envelope", max_length=64
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=ingestion.infrastructure.django.models._transient_default_expiry,
                        help_text="Cleanup job purges rows past this timestamp (default +24h)",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the submission successfully produces an analysis (one-to-one in practice)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="platform_core.contractanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Submission",
                "verbose_name_plural": "Contract Submissions",
                "db_table": "contract_submission",
            },
        ),
        migrations.CreateModel(
            name="OcrJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("pypdf", "pypdf (PDF con texto extraíble)"),
                            ("vision_llm", "Vision LLM (OpenRouter)"),
                            ("tesseract", "Tesseract local (fallback)"),
                        ],
                        help_text="Strategy used in this attempt",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, help_text="When the job started")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the job finished (NULL while running)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En ejecución"),
                            ("success", "Éxito"),
                            ("failed", "Fallido"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="running",
                        help_text="Outcome",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="", help_text="Truncated error message on failure")),
                ("error_code", models.CharField(blank=True, default="", help_text="Stable error code", max_length=64)),
                (
                    "tokens_consumed",
                    models.PositiveIntegerField(blank=True, help_text="LLM tokens spent (vision_llm only)", null=True),
                ),
                (
                    "cost_estimate_cents",
                    models.PositiveIntegerField(blank=True, help_text="Estimated call cost in USD cents", null=True),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(default=1, help_text="Attempt counter for this strategy"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=ingestion.infrastructure.django.models._transient_default_expiry,
                        help_text="Cleanup job purges rows past this timestamp (default +24h)",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Parent submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_jobs",
                        to="ingestion.contractsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR Job",
                "verbose_name_plural": "OCR Jobs",
                "db_table": "ocr_job",
            },
        ),
        migrations.AddIndex(
            model_name="contractsubmission",
            index=models.Index(fields=["submission_hash"], name="idx_submission_hash"),
        ),
        migrations.AddIndex(
            model_name="contractsubmission",
            index=models.Index(fields=["processing_status"], name="idx_submission_status"),
        ),
        migrations.AddIndex(
            model_name="contractsubmission",
            index=models.Index(fields=["expires_at"], name="idx_submission_expires"),
        ),
        migrations.AddIndex(
            model_name="contractsubmission",
            index=models.Index(fields=["analysis"], name="idx_submission_analysis"),
        ),
        migrations.AddConstraint(
            model_name="contractsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("file_count__gte", 1), ("file_count__lte", 50)),
                name="ck_submission_file_count_1_50",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "processing_status__in",
                        [
                            "received",
                            "extracting",
                            "extracted",
                            "classifying",
                            "analyzing",
                            "completed",
                            "failed_extraction",
                            "failed_classification",
                            "failed_analysis",
                            "rejected_language",
                            "rejected_type",
                            "rejected_size",
                            "expired",
                        ],
                    )
                ),
                name="ck_submission_processing_status_enum",
            ),
        ),
        migrations.AddIndex(
            model_name="ocrjob",
            index=models.Index(fields=["submission", "started_at"], name="idx_ocr_job_submission"),
        ),
        migrations.AddIndex(
            model_name="ocrjob",
            index=models.Index(fields=["status"], name="idx_ocr_job_status"),
        ),
        migrations.AddIndex(
            model_name="ocrjob",
            index=models.Index(fields=["expires_at"], name="idx_ocr_job_expires"),
        ),
        migrations.AddConstraint(
            model_name="ocrjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("strategy__in", ["pypdf", "vision_llm", "tesseract"])),
                name="ck_ocr_job_strategy_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="ocrjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["running", "success", "failed", "timeout", "cancelled"])),
                name="ck_ocr_job_status_enum",
            ),
        ),
    ]
