"""Casa Segura canonical legal copy — CS-337."""

from shared.legal.disclaimers import (
    CANONICAL_DISCLAIMER_LITERALS,
    DISCLAIMER_BLANK_GATE_LABEL_ES,
    DISCLAIMER_EMAIL_BODY_ES,
    DISCLAIMER_EXTENDED_FOOTER_ES,
    DISCLAIMER_FORBIDDEN_SUBSTRING,
    DISCLAIMER_ID,
    DISCLAIMER_REGISTRY_VERSION,
    DISCLAIMER_REPORT_HEADER_ES,
    DISCLAIMER_SHORT_ES,
    DISCLAIMER_SMS_SHORTHAND_ES,
    canonical_disclaimers,
)

__all__ = [
    "CANONICAL_DISCLAIMER_LITERALS",
    "DISCLAIMER_BLANK_GATE_LABEL_ES",
    "DISCLAIMER_EMAIL_BODY_ES",
    "DISCLAIMER_EXTENDED_FOOTER_ES",
    "DISCLAIMER_FORBIDDEN_SUBSTRING",
    "DISCLAIMER_ID",
    "DISCLAIMER_REGISTRY_VERSION",
    "DISCLAIMER_REPORT_HEADER_ES",
    "DISCLAIMER_SHORT_ES",
    "DISCLAIMER_SMS_SHORTHAND_ES",
    "canonical_disclaimers",
]
