# Generated by Django 5.2.14 on 2026-05-16 00:45

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RubricVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(help_text="Semver, e.g. 1.0.0", max_length=32, primary_key=True, serialize=False),
                ),
                ("released_at", models.DateTimeField(help_text="When this version was released")),
                ("criteria_count", models.PositiveIntegerField(help_text="Total criteria in this version")),
                ("categories", models.JSONField(help_text="Definition of categories and their global weights")),
                (
                    "criteria_definitions_path",
                    models.TextField(help_text="Path to the YAML file with the criteria for this version"),
                ),
                (
                    "changelog",
                    models.TextField(blank=True, default="", help_text="Summary of changes vs prior version"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Exactly one version may be active at a time (partial unique index enforces it)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubric Version",
                "verbose_name_plural": "Rubric Versions",
                "db_table": "rubric_version",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_rubric_version_active_singleton",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Criterion identifier within its rubric version, e.g. A1, B2, E7", max_length=8
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("A", "Legalidad básica"),
                            ("B", "Salud económica"),
                            ("C", "Estructura del contrato"),
                            ("D", "Garantías y saneamiento"),
                            ("E", "Cláusulas abusivas y derechos"),
                            ("F", "Cumplimiento específico por tipo"),
                        ],
                        help_text="Category A..F",
                        max_length=1,
                    ),
                ),
                ("title", models.CharField(help_text="Short title of the criterion", max_length=200)),
                ("description", models.TextField(help_text="What is being assessed")),
                (
                    "weight_in_category",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage weight within the category (0 < w <= 100)",
                        max_digits=5,
                    ),
                ),
                (
                    "applicable_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        help_text="Contract types this criterion applies to",
                        size=None,
                    ),
                ),
                (
                    "legal_anchor",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="Law articles it is based on, e.g. ['art-1605-cc', 'art-4-ley-inquilinato']",
                        size=None,
                    ),
                ),
                (
                    "override_code",
                    models.CharField(
                        blank=True,
                        help_text="OverrideCode triggered when this criterion fails critically (NULL if none)",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("evaluation_prompt", models.TextField(help_text="LLM prompt template for evaluating this criterion")),
                ("scoring_scale", models.JSONField(help_text="0-10 scale definition with textual criteria per band")),
                (
                    "worst_case_when_unverifiable",
                    models.DecimalField(
                        decimal_places=1,
                        default=4.0,
                        help_text="Score contributed when the criterion is unverifiable",
                        max_digits=3,
                    ),
                ),
                (
                    "rubric_version",
                    models.ForeignKey(
                        db_column="rubric_version",
                        help_text="Rubric version this criterion belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criteria",
                        to="rubric.rubricversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criterion",
                "verbose_name_plural": "Criteria",
                "db_table": "criterion",
                "indexes": [models.Index(fields=["rubric_version"], name="idx_criterion_rubric")],
                "constraints": [
                    models.UniqueConstraint(fields=("code", "rubric_version"), name="uq_criterion_code_rubric"),
                    models.CheckConstraint(
                        condition=models.Q(("weight_in_category__gt", 0), ("weight_in_category__lte", 100)),
                        name="ck_criterion_weight_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("category__in", ["A", "B", "C", "D", "E", "F"])),
                        name="ck_criterion_category_enum",
                    ),
                ],
            },
        ),
    ]
