# Generated by Django 5.2.14 on 2026-05-16 01:23

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rubric", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="criterion",
            index=django.contrib.postgres.indexes.GinIndex(fields=["applicable_types"], name="idx_criterion_types"),
        ),
    ]
